- name: Run bootstrap.sh
  script: bootstrap.sh
  register: python_path
  changed_when: "'Bootstrapping' in python_path.stdout"
  when: ansible_python_interpreter is not defined

- name: Set the python interpreter if needed
  set_fact: 
     ansible_python_interpreter: "{{ python_path.stdout_lines[python_path.stdout_lines|length-1] }}"
     python_bootstrap_needed: True
  when: ansible_python_interpreter is not defined

- name: Check if we need to install pip
  shell: "{{ansible_python_interpreter}} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false
  when: python_bootstrap_needed

- name: Copy get-pip.py
  copy: src=get-pip.py dest=/home/core/get-pip.py
  when: need_pip | failed

- name: Install pip
  shell: "{{ansible_python_interpreter}} get-pip.py"
  when: need_pip | failed

- name: Install pip launcher
  copy: src=runner dest=/home/core/bin/pip mode=0755

- name: Now gather facts
  setup:
